apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: consumer-triggers-cluster-binding
  namespace: bomc-tekton-pipelines
subjects:
- kind: ServiceAccount
  name: consumer-triggers-sa
  namespace: bomc-tekton-pipelines
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: consumer-triggers-cluster-role
---