apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bomc-tekton-pipelines

resources:
  - ./010-consumer-trigger-sa.yaml
  - ./020-consumer-trigger-role.yaml
  - ./030-consumer-trigger-role-binding.yaml
  - ./040-consumer-trigger-cluster-role.yaml
  - ./050-consumer-trigger-cluster-role-binding.yaml
  - ./060-consumer-trigger-template.yaml
  - ./070-consumer-trigger-binding.yaml
  - ./080-consumer-trigger.yaml
  - ./090-consumer-event-listener.yaml
  - ./100-consumer-evt-ingress.yaml

commonLabels:
  app.kubernetes.io/name: bomc-consumer-app

