apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: scan-image
  namespace: bomc-tekton-pipelines
spec:
  params:
  - name: IMAGE
    description: Reference of the image that will scan.
  - name: TAG
    description: Reference of the image buildah will produce.
  workspaces:
    - name: source
  steps:
  - name: trivy-scan-image
    image: aquasec/trivy:latest
    script: |
      set -e
      
      echo "bomc = $(params.IMAGE):$(params.TAG)"
      
      PATH_TO_IMAGE="$(params.IMAGE):$(params.TAG)"
      echo -e "Trivy Security Scan image in registry"
      #trivy image --exit-code 0 --input ${PATH_TO_IMAGE} | File input
      trivy image --exit-code 0 ${PATH_TO_IMAGE}
      #trivy image --exit-code 1 --severity CRITICAL --input ${PATH_TO_IMAGE} | File input
      trivy image --exit-code 1 --severity CRITICAL ${PATH_TO_IMAGE}
      my_exit_code=$?
      echo "Scan exit code :--- $my_exit_code"
      if [ ${my_exit_code} == 1 ]; then
        echo "Trivy scanning completed. CRITICAL Vulnerabilities found."
        exit 1
      else
        echo "Trivy scanning completed. CRITICAL vulnerabilities not found."
      fi
