apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: curl-check-content-registry-repository-run
  namespace: bomc-tekton-pipelines
spec:
  params:
    - name: curl-url
      value: "http://registry.kube-system.svc.cluster.local:80/v2/bomc/consumer/tags/list"
    - name: curl-options
      value:
       - "-v"
  taskRef:
    name: curl