apiVersion: tekton.dev/v1beta1
kind: PipelineResource
metadata:
  name: consumer-image
  namespace: tekton-pipelines
spec:
  type: image
  params:
  - name: url
    value: registry.kube-system.svc.cluster.local/bomc/consumer
  - name: revision
    value: main