apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-java-app
spec:
  workspaces:
  - name: output

  steps:
  - name: build-sources
    image: gradle:6.7.1-jdk11-hotspot
    workingDir: "$(workspaces.output.path)/."
    script: |
      #!/bin/sh
      set -o errexit
      gradle clean build
    securityContext:
      runAsUser: 0

  - name: build-image
    image: quay.io/buildah/stable:latest
    workingDir: "$(workspaces.output.path)/"
    command: ['buildah', 'bud', '--tls-verify=false', '--layers', '-f', 'Dockerfile', '-t', 'consumer_buildah:1.0.0', '.']
    volumeMounts:
    - name: varlibc
      mountPath: /var/lib/containers
    securityContext:
      allowPrivilegeEscalation: true
      runAsUser: 0
      privileged: true
      
  volumes:
  - name: varlibc
    emptyDir: {}
---
