apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: consumer-build-java-app
  #namespace: tekton-pipelines
spec:
  taskRef:
    name: build-java-app
  workspaces:
  - name: output
    persistentVolumeClaim:
      claimName: tekton-workspace-pvc
