apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy
spec:
  params:
  - name: CONFIG_GIT_URL
    default: ""
  - name: NEW_TAG
    default: latest
  - name: ARGO_APP_NAME
    default: ""
  workspaces:
  - name: config-source
  stepTemplate:
    envFrom:
    - secretRef:
        name: argocd-env-secret
    env:
    - name: ARGOCD_SERVER
      value: argocd-server.argocd:80

  steps:
  - name: git-checkout
    image: alpine/git:v2.26.2
    workingDir: "$(workspaces.config-source.path)/."
    script: |
      #!/usr/bin/env sh
      set -e

      cd deployment/overlays/prod
      
      echo "$(ls -alR)"
      
      cat kustomization.yaml
      
      #echo "updating $(inputs.params.environment) image to $(inputs.params.appImage):$(inputs.params.buildRevision)"
      echo "updating pod to newTag $(inputs.params.NEW_TAG)"
      #sed -i "s#newTag: \"[a-zA-Z0-9]\\+\"#newTag: \"$(inputs.params.NEW_TAG)\"#" kustomization.yaml
      sed -i "s#newTag: [a-zA-Z0-9]\\+#newTag: $(inputs.params.NEW_TAG)#" kustomization.yaml
      
      cat kustomization.yaml
      
  - name: commit-push-changes-gitops
    image: alpine/git:v2.26.2
    workingDir: "$(workspaces.config-source.path)"
    script: |
      #!/usr/bin/env sh
      set -e

      git config --global user.email michael_boerner@t-online.de
      git config --global user.name bomc

      
      echo "_git status"
      git status
      
      echo "_git add/commit_"
      git add .
      git commit --allow-empty -m "[tekton] updating image to $(inputs.params.NEW_TAG)"
      #eval $(ssh-agent)
      #ssh-add ~/.ssh/id_*
      echo "_git push_"
      
      git push

  - name: wait-for-argocd-rollout
    image: argoproj/argocd:v2.0.0
    script: |
      #!/usr/bin/env sh
      set -e

      #argocd login ${ARGOCD_SERVER} --username admin --password bomc --grpc-web-root-path /argo-cd
      argocd app sync $(inputs.params.ARGO_APP_NAME) --insecure
      #argocd app wait $(inputs.params.ARGO_APP_NAME) --sync --health --operation --insecure
---