apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy
spec:
  params:
  - name: ARGO_APP_NAME
    default: ""
  workspaces:
  - name: config-source
  stepTemplate:
    envFrom:
    - secretRef:
        name: argocd-env-secret
    env:
    - name: ARGOCD_SERVER
      value: argocd-server.argocd.svc.cluster.local:80

  steps:
  - name: wait-for-argocd-rollout
    image: argoproj/argocd:v2.0.0
    script: |
      #!/usr/bin/env sh
      set -e

      #argocd login $ARGOCD_SERVER --grpc-web-root-path /argo-cd --username $ARGOCD_USERNAME --password $ARGOCD_PASSWORD
      #argocd login $(inputs.params.ARGO_APP_NAME) --insecure --loglevel debug
      argocd app sync $(inputs.params.ARGO_APP_NAME) --loglevel debug --timeout 1200 --grpc-web-root-path /argocd --insecure
      #argocd app wait $(inputs.params.ARGO_APP_NAME) --sync --health --operation --insecure --grpc-web-root-path /argocd/
---