apiVersion: v1
kind: Secret
metadata:
  name: git-ssh
  namespace: bomc-tekton-pipelines
  annotations:
    tekton.dev/git-0: github.com
type: kubernetes.io/ssh-auth
data:
  ssh-privatekey: ${ENV_PRIVATE_KEY}
---
