# Generates a tekton user in argocd.
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  accounts.tekton: apiKey, login
---
# If a configmap is already available, git repositories will be set in config-map too. 
# The config-map must be merged with kubectl patch.
# kubectl patch configmap/argocd-cm -n argocd --type merge -p '{"data":{"accounts.tekton":"apiKey, login"}}'