# Run this secret in the namespace of the deployed tekton tasks and tekton pipelines.
apiVersion: v1
kind: Secret
metadata:
  name: argocd-env-secret
  namespace: bomc-tekton-pipelines
type: Opaque
data:
  # Encode the token from argcd by base64.
  ARGOCD_AUTH_TOKEN: ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SnFkR2tpT2lKaWIyMWpJaXdpYVdGMElqb3hOakkzTlRRNE56SXdMQ0pwYzNNaU9pSmhjbWR2WTJRaUxDSnVZbVlpT2pFMk1qYzFORGczTWpBc0luTjFZaUk2SW5SbGEzUnZianBoY0dsTFpYa2lmUS5TOHJXbDRPcmp6M09KbzZyeFhmLWp3NWQ2NTVXZk9uMG9OeVd6NE5RbF9B
---
