apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ambassador

commonLabels:
  app.kubernetes.io/name: bomc-ambassador
  
resources:
- 010-ambassador-namespace.yaml
- 020-ambassador-crds.yaml
- 030-ambassador-rbac.yaml
- 040-ambassador-loadbalancer-svc.yaml

patchesJson6902:
- target:
    group: rbac.authorization.k8s.io
    version: v1beta1
    kind: ClusterRoleBinding
    name: ambassador
  path: ./patches/argocd-clusterrolebinding-namespace-patch.yaml
