apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: bomc-app
  
resources:
- 010-tekton-git-ssh-secret.yaml
- 020-tekton-service-account.yaml
- 030-argocd-config-map.yaml
- 040-argocd-rbac-config-map.yaml
#- 050-argocd-env-secret.yaml

