apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: test-taskrun
  namespace: tekton-pipelines
spec:
  serviceAccountName: pipeline
  taskSpec:
    params:
    - name: buildRevision
    - name: appGitUrl
    workspaces:
    - name: app-source

    steps:
    - name: test-git-ssh
      image: alpine/git:v2.26.2
      workingDir: "$(workspaces.app-source.path)"
      script: |
        #!/usr/bin/env sh
        set -e
        
        eval $(ssh-agent)
        ssh-add ~/.ssh/id_*
        
        git config --global core.sshCommand 'ssh -o StrictHostKeyChecking=accept-new'
        
        git init
        git remote add origin $(params.appGitUrl)
        git fetch --depth 1 origin $(params.buildRevision)
        git checkout FETCH_HEAD
        
        ls -rla
        
        git config --global user.email "michael_boerner@t-online.de"
        git config --global user.name "bomc"
        
        # Create a new file and push it to the repository.
        touch initial
        
        git add initial
        git commit -m "add initial"
        
        eval $(ssh-agent)
        ssh-add ~/.ssh/id_*
        git push origin HEAD:main

  params:
  - name: buildRevision
    value: 'main'
  - name: appGitUrl
    value: 'git@github.com:bomc/micro-env-consumer-app.git'
  workspaces:
  - name: app-source
    emptyDir: {}
---
